apiVersion: apps/v1
kind: Deployment
metadata:
  name: bislist-deployment
  labels:
    app: bislist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bislist
  template:
    metadata:
      labels:
        app: bislist
    spec:
      containers:
      - name: bislist
        image: bislist:0.1.0
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: bislist-lb
spec:
  selector:
    app: bislist
  ports:
    - name: bislist-http
      port: 80
      targetPort: 5000
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 172.27.255.201
---
kind: Service
apiVersion: v1
metadata:
  name: bislist-service
spec:
  type: ClusterIP
  selector:
    app: bislist
  ports:
  - port: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bislist-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      sub_filter_once off;
      sub_filter '<a href="/' '<a href="/bis/';
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /bis(/|$)(.*)
        backend:
          service:
            name: bislist-service
            port:
              number: 5000
