DROP TABLE IF EXISTS posts;

CREATE TABLE items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    item_name TEXT NOT NULL UNIQUE,
    item_id INTEGER NOT NULL UNIQUE
);